src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Length;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Name;

    #[ORM\Column(type: 'datetime')]
    private $CreatedAt;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $CatchPhrase;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Category;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Author;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getCatchPhrase(): ?string
    {
        return $this->CatchPhrase;
    }

    public function setCatchPhrase(?string $CatchPhrase): self
    {
        $this->CatchPhrase = $CatchPhrase;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(?string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(?string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: '/')]
    public function index(EntityManagerInterface $manager): Response
    {
        $articles = $manager->getRepository(Article::class)->findBy([], ['id' => 'DESC']);

        return $this->render('/home/index.html.twig', [
            'articles' => $articles,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
        <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
                <h1 class="display-4 font-italic">Blog de cuisine</h1>
                <p class="lead my-3">Ici de nombreuses recettes peuvent être partagées.</p>
            </div>
        </div>

        <div class="row mb-2">

            {% for article in articles %}
                <div class="col-md-6 mb-3">
                    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <div class="mb-1 text-muted">{{ article.createdAt | date("d/m/Y") }}</div>
                            <strong class="d-inline-block mb-2 text-primary">{{ article.category }}</strong>
                            <h3 class="mb-0">{{ article.name }}</h3>
                            <h5 class="card-text mb-auto">- {{ article.catchphrase }} -</h5>
                            <p>{{ article.content }}</p>
                            <div>
                                <a href="{{ path('article/edit', {id: article.id}) }}" class="text-info">Editer</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
{% endblock %}