src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\Length;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Name;

    #[ORM\Column(type: 'datetime')]
    private $CreatedAt;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $CatchPhrase;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Category;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Author;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getCatchPhrase(): ?string
    {
        return $this->CatchPhrase;
    }

    public function setCatchPhrase(?string $CatchPhrase): self
    {
        $this->CatchPhrase = $CatchPhrase;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(?string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(?string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Name', TextType::class, ['label' => 'Titre'])
            ->add('CatchPhrase', TextType::class, ['label' => 'Description'])
            ->add('content', TextareaType::class, ['label' => 'Text'])
            ->add('Category', TextType::class, ['label' => 'Catégorie'])
            ->add('Author', TextType::class, ['label' => 'Auteur'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{

    public function __construct(EntityManagerInterface $manager)
    {
        $this->manager = $manager;
    }

    #[Route('/article')]
    public function index(): Response
    {
        $articles = $this->manager->getRepository(Article::class)->findBy([], ['id' => 'DESC']);

        return $this->render('article/index.html.twig', [
            'articles' => $articles
        ]);
    }

    #[Route('/article/add', name: "/article/add")]
    public function add(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $this->manager->persist($article);
            $this->manager->flush();

            return $this->redirectToRoute('/');
        }

        return $this->render('article/form.html.twig', [
            'form' => $form->createView(),
            'title' => "Création d'un article",
            'buttonText' => "Créer"
        ]);
    }

    #[Route('article/edit/{id}', name: "article/edit")]
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $this->manager->flush();

            return $this->redirectToRoute('/');
        }

        return $this->render('article/form.html.twig', [
            'form' => $form->createView(),
            'title' => "Édition d'un article",
            'buttonText' => "Modifier"
        ]);
    }
}

templates/article/form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <main class="page-content">
        <div class="container-fluid">
            <h1>{{ title }}</h1>
            <hr>
                {{ form_start(form) }}
                    {{ form_row(form.Name) }}
                    {{ form_row(form.CatchPhrase) }}
                    {{ form_row(form.content) }}
                    {{ form_row(form.Category) }}
                    {{ form_row(form.Author) }}

                    <button type="submit" class="btn btn-primary">{{ buttonText }}</button>
                {{ form_end(form) }}
        </div>
    </main>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <main class="page-content">
        <div class="container-fluid">
            <h1 class="d-flex w-100">
                <span>Articles</span>
                <a href="{{path('app_admin_article_add')}}" class="text-info ml-auto text-decoration-none">
                    +
                </a>
            </h1>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Titre</th>
                        <th>Content</th>
                        <th>Auteur</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for article in articles %}
                    <tr>
                        <td>{{ article.id }}</td>
                        <td>{{ article.name }}</td>
                        <td>{{ article.Content }}</td>
                        <td>{{ article.author }}</td>
                        <td>
                            <a href="#" class="text-info">Voir</a>
                            <a href="{{ path('/', {id: article.id}) }}" class="text-info">Editer</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock %}